language: objective-c
osx_image: xcode8
xcode_project: TOCropViewControllerExample.xcodeproj
xcode_scheme: TOCropViewControllerTests
script: set -o pipefail && xcodebuild -project "TOCropViewControllerExample.xcodeproj" -scheme "TOCropViewControllerTests" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean test | xcpretty
